import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import "./styles.css";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
            <title>Greetings from a sample Next.js app!</title>
            <meta content='website' property='og:type'/>
            <meta content='https://cdn.scalingo.com/homepage/assets/fb-33a6a93ddbf90bfdae57407481aa05a4.png'
                  property='og:image'/>
            <meta
                content="Deploying your own Next.js app on Scalingo is as easy as pie: JUST CLICK THIS BUTTON! It will be up in less than 2 minutes!"
                property='og:description'/>
            <meta charSet="utf-8"/>
            <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
            <meta httpEquiv="x-ua-compatible" content="ie=edge"/>
            <link rel="shortcut icon" href="https://scalingo.com/favicon.ico" type="image/vnd.microsoft.icon"/>
            <link href="https://fonts.googleapis.com/css?family=Roboto:300,500&display=optional" rel="stylesheet"/>
        </head>
        <body className={inter.className}>
        <div className="flex flex-col items-center">
            <div>{children}</div>
            <footer className="text-center">
                <p className="block p-4">
                <span className='block'><a
                    href="https://scalingo.com">Scalingo</a> is the best Platform as a Service on the market:</span>
                    no server to install, no dependencies to install, just push your code!
                </p>
            </footer>
        </div>
        </body>
        </html>
    );
}
